image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .

test:
  stage: test
  script:
    - apk add --no-cache build-base go
    - helm init --client-only
    - helm dependency build .
    - cd test && GO111MODULE=auto go test .

