image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"

stages:
  - test

lint:
  stage: test
  script:
    - helm lint .

test:
  stage: test
  script:
    - helm init --client-only
    - helm dependency build .

